file = {
    "init.moon",
    "elements/box.moon",
    "elements/element.moon",
    "elements/text.moon",
    "elements/window.moon",
    "extensions/streamlined_get_set.moon",
    "main.moon",
    "util.moon",
    "Element.luadoc",
}

project = "Pop.Box()"
description = "GUI library for [LÖVE](https://love2d.org/), designed for ease of use"
title = "Documentation"
--package = "pop" --has to be same name as source directory
format = "markdown"
dir = "docs"
